from __future__ import annotations

from enum import StrEnum


class CoverageStatus(StrEnum):
    FULL_STATIC = "FULL_STATIC"
    ROUTE_QUERY_ONLY = "ROUTE_QUERY_ONLY"
    REALTIME_ONLY = "REALTIME_ONLY"
    PARTIAL = "PARTIAL"
    UNAVAILABLE = "UNAVAILABLE"


class SourceKind(StrEnum):
    OPEN_API = "OPEN_API"
    PUBLIC_DATASET = "PUBLIC_DATASET"
    DOWNLOAD_FILE = "DOWNLOAD_FILE"
    GTFS = "GTFS"
    OFFICIAL_WEB = "OFFICIAL_WEB"
    OPERATOR_REQUEST = "OPERATOR_REQUEST"


class SourceAccessStatus(StrEnum):
    ENABLED = "ENABLED"
    DISABLED_ROBOTS = "DISABLED_ROBOTS"
    DISABLED_TERMS = "DISABLED_TERMS"
    DISABLED_TECHNICAL = "DISABLED_TECHNICAL"
    PENDING_KEY = "PENDING_KEY"
    PENDING_REVIEW = "PENDING_REVIEW"


class QualitySeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    FATAL = "FATAL"


class SyncStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED_UNCHANGED = "SKIPPED_UNCHANGED"
    CANCELLED = "CANCELLED"
